favicon: /favicon.ico
banner: /img/webstack_banner_cn.png

logo:
  expanded: /img/logo@2x.png
  collapsed: /img/logo-collapsed@2x.png
  dark: /img/logo_dark@2x.png

flag:
  icon: flag-cn
  name: Chinese

search: false

githubCorner: '<a href="https://github.com/Setobox/webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

menu:
  - name: 快速启动
    icon: far fa-star
    config: quickstart
  - name: 代码托管
    icon: far fa-star
    config: hosting
  - name: 文档速查
    icon: far fa-book
    config: document
  - name: 实用工具
    icon: far fa-star
    config: nbTools
  - name: 趣味网站
    icon: fas fa-tools
    config: funSite
  - name: 我的博客
    icon: fas fa-blog
    config: mySite
    # submenu:
    #   - name: 开发工具
    #     icon: fas fa-tools
    #     config: devTools
    #   - name: 我的博客
    #     icon: fas fa-blog
    #     config: myBlog

quickstart:
  - name: GitHub
    url: https://github.com/    # /child
    img: /img/logos/github1.png
    description: 面向开源及私有软件项目的托管平台
  - name: BiliBili
    url: https://www.bilibili.com/   
    img: /img/logos/bilibili3.png
    description: 全国最大同性交友平台
  - name: Vercel
    url: https://vercel.com/dashboard    
    img: /img/logos/browser1.png
    description: 静态网站托管平台
  - name: 腾讯云函数
    url: https://console.cloud.tencent.com/scf/list   
    img: /img/logos/browser1.png
    description: 云函数
  - name: LeetCode
    url: https://leetcode-cn.com/
    img: /img/logos/browser1.png
    description: 全球极客挚爱的技术成长平台
  # - name: 
  #   url: 
  #   img: /img/logos/browser1.png
  #   description: 
# 

hosting:
  - name: Github
    url: https://github.com/
    img: /img/logos/github1.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Vercel
    url: https://vercel.com/dashboard    
    img: /img/logos/browser1.png
    description: 静态网站托管平台
  - name: Coding
    url: https://vercel.com/dashboard    
    img: /img/logos/browser1.png
    description: 国内首个一站式云端软件服务平台
  - name: Gitee
    url: https://vercel.com/dashboard    
    img: /img/logos/browser1.png
    description: 国内最大的托管平台

document:
  - name: HTML5
    url: https://www.runoob.com/html/html5-intro.html   
    img: /img/logos/browser1.png
    description: HTML5菜鸟教程
  - name: CSS
    url: https://www.runoob.com/css/css-tutorial.html  
    img: /img/logos/browser1.png
    description: CSS/CSS3菜鸟教程
  - name: JavaScript
    url: https://www.runoob.com/js/js-tutorial.html   
    img: /img/logos/browser1.png
    description: JS菜鸟教程
  - name: JQuery
    url: https://www.runoob.com/jquery/jquery-tutorial.html   
    img: /img/logos/browser1.png
    description: JQ菜鸟教程
  - name: Vue3
    url: https://www.runoob.com/vue3/vue3-tutorial.html   
    img: /img/logos/browser1.png
    description: Vue3菜鸟教程
  - name: BootStrap
    url: https://www.runoob.com/bootstrap/bootstrap-tutorial.html   
    img: /img/logos/browser1.png
    description: BootStrap菜鸟教程
  - name: Python3
    url: https://www.runoob.com/python3/python3-tutorial.html   
    img: /img/logos/browser1.png
    description: Python菜鸟教程
  - name: Sql
    url: https://www.runoob.com/sql/sql-tutorial.html   
    img: /img/logos/browser1.png
    description: Sql语句菜鸟教程
  - name: Android
    url: https://developer.android.google.cn/guide   
    img: /img/logos/browser1.png
    description: Android开发文档

nbTools:
  - name: 测速网
    url: https://www.speedtest.cn/
    img: /img/logos/browser1.png
    description: speedtest国内测速
  - name: 测速网
    url: http://aaaaaa.speedtestcustom.com/
    img: /img/logos/browser1.png
    description: speedtest外网测速
  - name: 表格转换
    url: https://tableconvert.com/
    img: /img/logos/browser1.png
    description: md,yaml,json,xml等多格式互相转换
  - name: 正则测试
    url: https://regex101.com/
    img: /img/logos/regex.png
    description: 测试正则表达式
  - name: 图片压缩
    url: https://tinypng.com/
    img: /img/logos/browser1.png
    description: 免费压缩图片
  - name: 小码短链接
    url: https://xiaomark.com/
    img: /img/logos/browser1.png
    description: 将长链接缩短
  - name: 皮卡智能
    url: http://www.picup.shop/?ref=appinn
    img: /img/logos/browser1.png
    description: 一键抠图
  - name: 拾取坐标系统
    url: http://api.map.baidu.com/lbsapi/getpoint/
    img: /img/logos/browser1.png
    description: 百度地图拾取坐标
  - name: 10分钟邮箱
    url: https://10minutemail.net/m/
    img: /img/logos/browser1.png
    description: 临时邮箱


funSite:
  - name: 
    url: https://aidn.jp/mikutap/
    img: /img/logos/browser1.png
    description: 无论怎么点都很好听


mySite:
  - name: Setobox Blog
    url: https://blog.setobox.me/
    img: /img/logos/myblog.jpg
    description: 姬顶盒的博客

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/Setobox/webstack">webstack</a>的导航站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: Setobox
    url: https://blog.setobox.me/
    img: /img/logos/myblog.jpg
    description: 懒人一个
    html: '<br /><blockquote><p>本站是<a href="https://github.com/Setobox">Setobox</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2021

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
